services:
  app:
    image: ghcr.io/osama5663/garage:latest
    env_file:
      - .env
    environment:
      MARIADB_HOST: mariadb
      PORT: 8082
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - "8082"
    restart: unless-stopped
    networks:
      - garage
    volumes:
      - ./uploads:/app/uploads
      - ./storage:/app/storage

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app
    networks:
      - garage
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d

  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - garage
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  garage:
