import { formatCurrency as baseFormatCurrency, formatDate as baseFormatDate } from './formatters'

// CSV Export Function
export const exportToCSV = (data: any[], filename: string) => {
  if (data.length === 0) {
    alert('No data to export')
    return
  }

  // Get headers from first object
  const headers = Object.keys(data[0])
  
  // Create CSV content
  const csvContent = [
    headers.join(','), // Header row
    ...data.map(row => 
      headers.map(header => {
        const value = row[header]
        // Escape quotes and wrap in quotes if contains comma or quotes
        if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
          return `"${value.replace(/"/g, '""')}"`
        }
        return value
      }).join(',')
    )
  ].join('\n')

  // Create blob and download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)
  link.setAttribute('href', url)
  link.setAttribute('download', `${filename}.csv`)
  link.style.visibility = 'hidden'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

// PDF Export Function
export const exportToPDF = (data: any[], title: string, dateRange: { startDate: string; endDate: string }) => {
  if (data.length === 0) {
    alert('No data to export')
    return
  }

  const headers = Object.keys(data[0])
  
  // Create HTML table
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 20px;
          color: #333;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
          border-bottom: 2px solid #333;
          padding-bottom: 20px;
        }
        .header h1 {
          margin: 0;
          color: #2c3e50;
        }
        .date-range {
          text-align: center;
          margin-bottom: 30px;
          color: #666;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 20px;
        }
        th, td {
          border: 1px solid #ddd;
          padding: 12px;
          text-align: left;
        }
        th {
          background-color: #f8f9fa;
          font-weight: bold;
          color: #495057;
        }
        tr:nth-child(even) {
          background-color: #f8f9fa;
        }
        .summary {
          margin-top: 30px;
          padding: 20px;
          background-color: #f8f9fa;
          border-radius: 5px;
        }
        .footer {
          margin-top: 40px;
          text-align: center;
          color: #666;
          font-size: 12px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${title}</h1>
        <p>Garage Management System</p>
      </div>
      <div class="date-range">
        <p><strong>Report Period:</strong> ${new Date(dateRange.startDate).toLocaleDateString()} - ${new Date(dateRange.endDate).toLocaleDateString()}</p>
        <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
      </div>
      <table>
        <thead>
          <tr>
            ${headers.map(header => `<th>${header}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${data.map(row => 
            `<tr>${headers.map(header => `<td>${row[header] || ''}</td>`).join('')}</tr>`
          ).join('')}
        </tbody>
      </table>
      <div class="summary">
        <p><strong>Total Records:</strong> ${data.length}</p>
        <p><strong>Report Summary:</strong> This report contains ${data.length} records for the specified date range.</p>
      </div>
      <div class="footer">
        <p>Generated by GaragePro Management System</p>
      </div>
    </body>
    </html>
  `

  // Create a new window and print
  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(htmlContent)
    printWindow.document.close()
    printWindow.focus()
    
    // Wait for content to load, then print
    setTimeout(() => {
      printWindow.print()
    }, 250)
  } else {
    alert('Please allow popups to export PDF reports')
  }
}

// Format currency for reports (delegates to shared currency formatter)
export const formatCurrency = (amount: number) => {
  return baseFormatCurrency(amount)
}

// Format date for reports (delegates to shared date formatter)
export const formatDate = (dateString: string) => {
  return baseFormatDate(dateString)
}

// Generate filename with timestamp
export const generateFilename = (baseName: string, dateRange: { startDate: string; endDate: string }) => {
  const startDate = new Date(dateRange.startDate).toISOString().split('T')[0]
  const endDate = new Date(dateRange.endDate).toISOString().split('T')[0]
  const timestamp = new Date().toISOString().split('T')[0]
  return `${baseName}_${startDate}_to_${endDate}_${timestamp}`
}
